// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC8l4vxy4IdNBS40mu7RUnk3YlMt4W3Ao',
    appId: '1:986857521296:web:029298d4e2ce73cde39815',
    messagingSenderId: '986857521296',
    projectId: 'importexport-95eae',
    authDomain: 'importexport-95eae.firebaseapp.com',
    storageBucket: 'importexport-95eae.appspot.com',
    measurementId: 'G-06NHGKVTQQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ8zm1E-JfgJS3tE4gZ35jbmeWr6USu5o',
    appId: '1:986857521296:android:b2d653dd9a8cba52e39815',
    messagingSenderId: '986857521296',
    projectId: 'importexport-95eae',
    storageBucket: 'importexport-95eae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe3Q06WyodwYYlW3cLVZDCYTWKBn_TTM8',
    appId: '1:986857521296:ios:4a7dcb7f01a6b9cae39815',
    messagingSenderId: '986857521296',
    projectId: 'importexport-95eae',
    storageBucket: 'importexport-95eae.appspot.com',
    iosBundleId: 'com.example.importexport',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBe3Q06WyodwYYlW3cLVZDCYTWKBn_TTM8',
    appId: '1:986857521296:ios:aed488675f4f40ebe39815',
    messagingSenderId: '986857521296',
    projectId: 'importexport-95eae',
    storageBucket: 'importexport-95eae.appspot.com',
    iosBundleId: 'com.example.importexport.RunnerTests',
  );
}
